/*
   -- deneyapKart --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__WIFI_POINT

#include <WiFi.h>

// RemoteXY connection settings
#define REMOTEXY_WIFI_SSID "RemoteXY"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377


#include <RemoteXY.h>

// RemoteXY GUI configuration
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =  // 45 bytes V19
  { 255, 4, 0, 0, 0, 38, 0, 19, 0, 0, 0, 0, 31, 1, 200, 84, 1, 1, 3, 0,
    5, 12, 11, 60, 60, 53, 2, 26, 31, 5, 132, 10, 60, 60, 0, 2, 26, 31, 130, 83,
    26, 40, 40, 24, 17 };

// this structure defines all the variables and events of your control interface
struct {

  // input variables
  int8_t joystick_01_x;  // from -100 to 100
  int8_t joystick_01_y;  // from -100 to 100
  int8_t joystick_02_x;  // from -100 to 100
  int8_t joystick_02_y;  // from -100 to 100

  // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#include <Deneyap_Servo.h>

Servo servo1;  // 1. servo motor için class tanımlanması
Servo servo2;  // 2. servo motor için class tanımlanması
Servo servo3;  // 3. servo motor için class tanımlanması
Servo servo4; 

void setup() {
  RemoteXY_Init();  // initialization by macros

  servo1.attach(D8);     // 1. servo motorun D3 pinin ve 0 kanal ayarlanması  /*attach(pin, channel=0, freq=50, resolution=12) olarak belirlenmiştir. Kullandığınız motora göre değiştirebilirsiniz */
  servo2.attach(D4, 1);  // 2. servo motorun D4 pinin ve 1 kanal ayarlanması
  servo3.attach(D5, 2);  // 3. servo motorun D5 pinin ve 3 kanal ayarlanması
  servo4.attach(D6, 3);

  servo1.write(90);  // 1. servo motorun milinin 30 derece dönmesi
  servo2.write(90);  // 2. servo motorun milinin 60 derece dönmesi
  servo3.write(90);  // 3. servo motorun milinin 90 derece dönmesi
  servo4.write(90);

  RemoteXY_delay(500);
  // TODO you setup code
}

void loop() {
  RemoteXY_Handler();
  int joy1X = map(RemoteXY.joystick_01_x, -100, 100, 1, 179);
  int joy1Y = map(RemoteXY.joystick_01_y, -100, 100, 1, 179);
  int joy2X = map(RemoteXY.joystick_02_x, -100, 100, 1, 179);
  int joy2Y = map(RemoteXY.joystick_02_y, -100, 100, 1, 179);

  servo1.write(joy1X);
  servo2.write(joy1Y);
  servo3.write(joy2X);
  servo4.write(joy2Y);
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay()
  RemoteXY_delay(50);
}
